### ISSUE TITLE
Slight delay after zooming before page becomes interactive 

### ISSUE THREAD

**Issue by haxiomic** [haxiomic/firefox-multi-touch-zoom#14]
It seems that when the scroll bars are made active after zooming the page is re-built which causes a noticeable hang

This work should be avoidable but I haven't yet found a work around

**Comment by mattiad** [comment]
How to reproduce this error?

**Comment by haxiomic** [comment]
If I zoom-in and immediately try two-finger panning, there's often a wait of about a few hundred ms to 1s before the panning works. If I run a performance recording in the dev tools there's a framerate drop right after the zoom where it does a 'layout' and a then a long 'paint' operation.

If I don't enable the scrollbars then this repaint doesn't occur but you can no longer pan

I'm on a recent Macbook Pro and I've seen it happen under Windows so I've assuemd it's happening for everyone else but it's possible that it doesn't occur on your setup

**Comment by QWERTYUIOPYOZO** [comment]
simply add in:
`"run_at": "document_start"`
after
`"matches": ["<all_urls>"],
"js": ["pinch-zoom.js"],`
in `manifest.json`

**Comment by QWERTYUIOPYOZO** [comment]
I have fixed this issue by using `requestAnimationFrame`
I have patched it here:
[https://github.com/haxiomic/firefox-multi-touch-zoom/pull/15](url)

**Comment by haxiomic** [comment]
Unfortunately this doesn't resolve the issue for me, see comment https://github.com/haxiomic/firefox-multi-touch-zoom/pull/15/files#r178283167
